language: go

go:
  - 1.5
  - 1.6
  - 1.7
  - tip

install:
  - github.com/peterh/liner

script:
  - go vet ./...
  - go test -v ./...
  - GOFMT=$(gofmt -d -s .) && echo $GOFMT && test -z "$GOFMT"

after_success:
- coveralls
