// Code generated by "stringer -type=matchType"; DO NOT EDIT

package prompt

import "fmt"

const _matchType_name = "matchNonematchWildcardmatchSubstitutionmatchExact"

var _matchType_index = [...]uint8{0, 9, 22, 39, 49}

func (i matchType) String() string {
	if i >= matchType(len(_matchType_index)-1) {
		return fmt.Sprintf("matchType(%d)", i)
	}
	return _matchType_name[_matchType_index[i]:_matchType_index[i+1]]
}
