// Code generated by "stringer -type=segmentType"; DO NOT EDIT

package prompt

import "fmt"

const _segmentType_name = "wordTypeplaceholderType"

var _segmentType_index = [...]uint8{0, 8, 23}

func (i segmentType) String() string {
	if i >= segmentType(len(_segmentType_index)-1) {
		return fmt.Sprintf("segmentType(%d)", i)
	}
	return _segmentType_name[_segmentType_index[i]:_segmentType_index[i+1]]
}
